---
title: "Causes of Death "
subtitle: "Presentation"
author: "Min Min Soh"
institute: "Department of Econometrics and Business Statistics"
output:
  xaringan::moon_reader:
    lib_dir: libs
    css: css/style.css
    yolo: FALSE
---


```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)
```

```{r , echo = FALSE, message = FALSE, warning = FALSE}
library(tidyverse)
library(datasets)
library(kableExtra)
```


class: center, middle

# Introduction 

Research Questions 

```{r read_csv, echo = FALSE, message = FALSE, warning = FALSE}
Deaths <- read_csv("Data/annual-number-of-deaths-by-cause.csv")
```

---

# Deaths - HIV/AIDS

- .blue[How is the death rates of **HIV / AIDS** change in the world ? ]
- .blue[What is the top 5 countries with the highest death rates from HIV / AIDS ? ]
- .blue[What are the preventive measures for HIV / AIDS ? ]


---

.content-box-soft[ 
Deaths rates from HIV/AIDS across the world
]

```{r HIV_AIDS,  echo = FALSE, message = FALSE, warning = FALSE }
HIV_AIDS <- Deaths %>% 
  select( Entity, Code, Year, `Deaths - HIV/AIDS - Sex: Both - Age: All Ages (Number)`) %>%
  rename(Deaths_HIV_AIDS = `Deaths - HIV/AIDS - Sex: Both - Age: All Ages (Number)` )%>%
  filter(!is.na(Deaths_HIV_AIDS))
                
                 
```






---

```{r endslide, child="EndSlide/endslide.Rmd"}
```  

